version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 8.0
    build:
        commands:
            - echo Deployment started on `date` for function MyFirstLambda
            - export PATH="$PATH:/root/.dotnet/tools"
            - dotnet new --install Amazon.Lambda.Templates::*
            - dotnet tool install -g Amazon.Lambda.Tools
            - cd Learn.Lambda
            - dotnet lambda deploy-function --MyFirstLambda
 